### ISSUE TITLE
Test dei risultati

### ISSUE THREAD

**Issue by p1ndsvin** [AndreaGuerry/Lam-info-2022#2]
Sviluppa una funzione che carica il numpy vector (con numpy.load) e verifica che la label predetta dal classificatore sia quella che ti aspetti. Nel caso di una misclassification di un 5, ti aspetti una label diversa da 5.

**Comment by p1ndsvin** [comment]
Riesci a sviluppare entro oggi?

**Comment by AndreaGuerry** [comment]
se riesco a mangiare il mio gelato
